# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.8'

services:

  mqutils:
    container_name: 'mqutils'
    build:
      context: '.'
      dockerfile: 'DockerfileLocal'
    tty: true
    volumes:
      # App
      - './:/home/appuser'
      # Logs
      - './logs:/home/appuser/logs'
    env_file:
      - '.env'
    # Join this service to a custom docker network
    networks:
      - drsts-net
    ports:
      - "10581:8443"
networks:
  drsts-net:
    name: "drsts-net"