name: Import Management Service

on:
  push:
  pull_request:
    branches:
      - main
      - trial

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.10.2 environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10.2"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          pip install -U pyflakes
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run our unit tests
      - name: Run unit tests
        run: |
          pytest mqutils/tests/unit

      # Run Pyflakes
      - name: Run pyflakes
        run: |
          pyflakes mqutils
